# Generated by Django 3.2 on 2021-04-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_nn'),
    ]

    operations = [
        migrations.CreateModel(
            name='NNImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('thumbnail', models.ImageField(upload_to='nnimage_uploads')),
                ('trained', models.BooleanField()),
                ('detail_name', models.CharField(max_length=64, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_processing.category')),
                ('nn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.nn')),
            ],
        ),
        migrations.CreateModel(
            name='NNImageMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.PositiveSmallIntegerField()),
                ('y1', models.PositiveSmallIntegerField()),
                ('x2', models.PositiveSmallIntegerField()),
                ('y2', models.PositiveSmallIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_processing.nnimage')),
            ],
        ),
    ]
