# Generated by Django 3.2 on 2021-04-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_nn_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='nn',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
