# Generated by Django 3.2 on 2021-04-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0005_nn_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nnimage',
            name='category',
        ),
        migrations.AddField(
            model_name='nnimage',
            name='category',
            field=models.ManyToManyField(null=True, to='image_processing.Category'),
        ),
    ]
