# Generated by Django 3.2 on 2021-04-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0006_auto_20210425_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnimage',
            name='category',
            field=models.ManyToManyField(to='image_processing.Category'),
        ),
    ]
