# Generated by Django 3.2 on 2021-04-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0007_alter_nnimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nnimage',
            name='category',
        ),
        migrations.AddField(
            model_name='nnimagemarkup',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_processing.category'),
        ),
    ]
